name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt -r dev-requirements.txt

      - name: Run tests
        run: |
          pytest -q

      - name: Run Bandit (security scan)
        run: |
          python -m bandit -r . -ll --exclude venv,tests || true

      - name: Run pip-audit (dependency scan)
        run: |
          python -m pip_audit || true
